# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"


# swagger.yml

# ...

servers:
  - url: "/api"

components:
  schemas:
    Person:
      type: 'object'
      required:
        # fill info from the json data
        - lname
        properties:
          fname:
            type: 'string'
          lname:
            type: 'string'


  # swagger.yml

# ...

paths:
  /people:
    get:
      
    post:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"
